### ISSUE TITLE
Submit fails

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#5]
Error submitting valid data.

**Repro:**
- Fill form with correct data (I used iostest005@peptest.ch)
- submit

**Expected:**
- Next screen shown
- I receive a mail with confirmation link

**Actual:**
Error: 
Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)

**Additional Info:**
bers_dues18_11_paid', 'members_dues18_11_amount_paid', 'members_dues18_11_paid_date', 'members_dues18_12_invoice', 'members_dues18_12_│·····································································································
invoice_date', 'members_dues18_12_invoice_no', 'members_dues18_12_token', 'members_dues18_12_start', 'members_dues18_12_amount', 'memb│·····································································································
ers_dues18_12_reduced', 'members_dues18_12_balanced', 'members_dues18_12_paid', 'members_dues18_12_amount_paid', 'members_dues18_12_pa│·····································································································
id_date', 'members_member_type', 'members_fee')                                                                                       │·····································································································
{'city': u'city', 'password': u'12345', 'date_of_submission': datetime.datetime(2018, 4, 25, 15, 0, 9, 392886), 'firstname': u'fuenfeu│·····································································································
s', 'locale': u'en', 'address1': u'adr1', 'address2': u'adr2', 'member_type': u'individual', 'date_of_birth': datetime.date(1999, 1, 1│·····································································································
), 'postcode': u'12345', 'lastname': u'buffenEN', 'email_is_confirmed': False, 'num_shares': 1, 'country': u'GB', 'email': u'iostest00│·····································································································
5@peptest.ch', 'email_confirm_code': u'RZ7TQYCFTK'}                                                                                   │·····································································································
2018-04-25 15:00:09,461 INFO  [sqlalchemy.engine.base.Engine][Dummy-3] ROLLBACK                                                       │·····································································································
2018-04-25 15:00:09,462 DEBUG [txn.140099851335424][Dummy-3] abort                                                                    │·····································································································
2018-04-25 15:00:09,462 ERROR [waitress][Dummy-3] Exception when serving /                                                            │·····································································································
Traceback (most recent call last):                                                                                                    │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/channel.py", line 337, in service       │·····································································································
    task.service()                                                                                                                    │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 173, in service          │·····································································································
    self.execute()                                                                                                                    │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 392, in execute          │·····································································································
    app_iter = self.channel.server.application(env, start_response)                                                                   │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 242, in __call__         │·····································································································
    response = self.invoke_subrequest(request, use_tweens=True)                                                                       │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest│·····································································································
    response = handle_request(request)                                                                                                │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween     │·····································································································
    response = view_callable(exc, request)                                                                                            │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_│·····································································································
to_response                                                                                                                           │·····································································································
    result = view(context, request)                                                                                                   │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween     │·····································································································
    response = handler(request)                                                                                                       │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid_tm-0.8-py2.7.egg/pyramid_tm/__init__.py", line 92, in tm_tween    │·····································································································
    reraise(*exc_info)                                                                                                                │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid_tm-0.8-py2.7.egg/pyramid_tm/__init__.py", line 73, in tm_tween    │·····································································································
    response = handler(request)                                                                                                       │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request   │·····································································································
    response = view_callable(context, request)                                                                                        │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_vi│·····································································································
ew                                                                                                                                    │·····································································································
    result = view(context, request)                                                                                                   │·····································································································
  File "/home/coop-admin/.local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 501, in _requestonl│·····································································································
y_view                                                                                                                                │·····································································································
    response = view(request)                                                                                                          │·····································································································
  File "/home/coop-admin/PepCoopMembership/c3smembership/views/afm.py", line 458, in join_c3s                                         │·····································································································
    member = C3sMember(**coopMemberArgs)                                                                                              │·····································································································
  File "<string>", line 4, in __init__                                                                                                │·····································································································
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/state.py", line 306, in _initialize_instance                                      │·····································································································
    manager.dispatch.init_failure(self, args, kwargs)                                                                                 │·····································································································
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__                                            │·····································································································
    compat.reraise(exc_type, exc_value, exc_tb)                                                                                       │·····································································································
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/state.py", line 303, in _initialize_instance                                      │·····································································································
    return manager.original_init(*mixed[1:], **kwargs)                                                                                │·····································································································
  File "/home/coop-admin/PepCoopMembership/c3smembership/models.py", line 824, in __init__                                            │·····································································································
    self.fee = kwargs.pop('fee')                                                                                                      │·····································································································
KeyError: 'fee'

**Comment by ari-pep** [comment]
fixed
